
package cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ExameWS", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:8080/examews-web/ExameWS?wsdl")
public class ExameWS_Service
    extends Service
{

    private final static URL EXAMEWS_WSDL_LOCATION;
    private final static WebServiceException EXAMEWS_EXCEPTION;
    private final static QName EXAMEWS_QNAME = new QName("http://ws/", "ExameWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/examews-web/ExameWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXAMEWS_WSDL_LOCATION = url;
        EXAMEWS_EXCEPTION = e;
    }

    public ExameWS_Service() {
        super(__getWsdlLocation(), EXAMEWS_QNAME);
    }

    public ExameWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXAMEWS_QNAME, features);
    }

    public ExameWS_Service(URL wsdlLocation) {
        super(wsdlLocation, EXAMEWS_QNAME);
    }

    public ExameWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXAMEWS_QNAME, features);
    }

    public ExameWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExameWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExameWS
     */
    @WebEndpoint(name = "ExameWSImplPort")
    public ExameWS getExameWSImplPort() {
        return super.getPort(new QName("http://ws/", "ExameWSImplPort"), ExameWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExameWS
     */
    @WebEndpoint(name = "ExameWSImplPort")
    public ExameWS getExameWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "ExameWSImplPort"), ExameWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXAMEWS_EXCEPTION!= null) {
            throw EXAMEWS_EXCEPTION;
        }
        return EXAMEWS_WSDL_LOCATION;
    }

}
