
package cliente;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExameWS", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExameWS {


    /**
     * 
     * @param filtros
     * @return
     *     returns java.util.List<cliente.Exame>
     * @throws ErroIdException
     */
    @WebMethod(operationName = "TodosOsExames", action = "http://ws/ExameWS/TodosOsExamesRequest")
    @WebResult(name = "exame", targetNamespace = "")
    @RequestWrapper(localName = "TodosOsExames", targetNamespace = "http://ws/", className = "cliente.TodosOsExames")
    @ResponseWrapper(localName = "TodosOsExamesResponse", targetNamespace = "http://ws/", className = "cliente.TodosOsExamesResponse")
    @Action(input = "http://ws/ExameWS/TodosOsExamesRequest", output = "http://ws/ExameWS/TodosOsExamesResponse", fault = {
        @FaultAction(className = ErroIdException.class, value = "http://ws/ExameWS/TodosOsExames/Fault/ErroIdException")
    })
    public List<Exame> todosOsExames(
        @WebParam(name = "filtros", targetNamespace = "")
        Filtros filtros)
        throws ErroIdException
    ;

}
