package ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2020-07-20T19:25:48.482-03:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://ws/", name = "ExameWS")
@XmlSeeAlso({ObjectFactory.class})
public interface ExameWS {

    @WebMethod(operationName = "TodosOsExames")
    @Action(input = "http://ws/ExameWS/TodosOsExamesRequest", output = "http://ws/ExameWS/TodosOsExamesResponse", fault = {@FaultAction(className = ErroIdException.class, value = "http://ws/ExameWS/TodosOsExames/Fault/ErroIdException")})
    @RequestWrapper(localName = "TodosOsExames", targetNamespace = "http://ws/", className = "ws.TodosOsExames")
    @ResponseWrapper(localName = "TodosOsExamesResponse", targetNamespace = "http://ws/", className = "ws.TodosOsExamesResponse")
    @WebResult(name = "exame", targetNamespace = "")
    public java.util.List<ws.Exame> todosOsExames(
        @WebParam(name = "filtros", targetNamespace = "")
        ws.Filtros filtros
    ) throws ErroIdException;
}
